"""Real notification channels — proves the alert path actually works.

We deliberately avoid any heavyweight dependencies here: a Slack incoming
webhook is just an HTTP POST with a JSON body, and we already require
``httpx`` for the [server] / [ai] extras.

If httpx isn't installed (the bare CLI install), notify() returns
``{"sent": False, "reason": "httpx not installed"}`` so callers can
degrade gracefully — never raise.
"""

from __future__ import annotations

import json
import os
from typing import Any


SEVERITY_EMOJI = {
    "critical": ":rotating_light:",
    "high": ":warning:",
    "medium": ":small_orange_diamond:",
    "low": ":small_blue_diamond:",
    "info": ":information_source:",
}


def _format_slack_blocks(events: list[dict]) -> dict:
    """Produce a Slack Block Kit payload for a batch of events."""
    if not events:
        return {"text": "SafeCadence: no new findings."}

    crit = sum(1 for e in events if (e.get("severity") or "").lower() == "critical")
    high = sum(1 for e in events if (e.get("severity") or "").lower() == "high")
    headline = (
        f":shield: SafeCadence — {len(events)} new findings"
        f" ({crit} critical, {high} high)"
    )
    blocks: list[dict] = [
        {"type": "header", "text": {"type": "plain_text", "text": headline}},
    ]
    # Show up to 10 highest-severity events; everything else is summarised.
    rank = {"critical": 0, "high": 1, "medium": 2, "low": 3, "info": 4}
    sorted_events = sorted(events,
                            key=lambda e: rank.get((e.get("severity") or "info").lower(), 5))
    for e in sorted_events[:10]:
        sev = (e.get("severity") or "info").lower()
        emoji = SEVERITY_EMOJI.get(sev, "•")
        title = e.get("title") or e.get("type") or "finding"
        asset = e.get("asset_id") or e.get("subject") or ""
        why = e.get("why") or e.get("conflict") or e.get("evidence") or ""
        if isinstance(why, dict):
            why = json.dumps(why)
        blocks.append({
            "type": "section",
            "text": {
                "type": "mrkdwn",
                "text": (f"{emoji} *[{sev.upper()}] {title}*"
                         + (f"\n  asset: `{asset}`" if asset else "")
                         + (f"\n  {why}" if why else "")),
            },
        })
    if len(sorted_events) > 10:
        blocks.append({
            "type": "context",
            "elements": [{"type": "mrkdwn",
                          "text": f"_+{len(sorted_events) - 10} more not shown — "
                                  f"see `/api/policy/compliance` for the full list._"}],
        })
    blocks.append({
        "type": "context",
        "elements": [{"type": "mrkdwn",
                      "text": "Generated by SafeCadence — local-first network "
                              "+ identity security platform."}],
    })
    return {"text": headline, "blocks": blocks}


def notify_slack(webhook_url: str, events: list[dict],
                 *, timeout: int = 10,
                 signing_secret: str | None = None) -> dict[str, Any]:
    """POST a Block Kit payload to a Slack incoming-webhook URL.

    Returns ``{"sent": bool, "status": int, "reason": str}``. Never
    raises — callers expect a quiet, graceful failure when networks
    are unavailable.
    """
    if not webhook_url:
        return {"sent": False, "reason": "no webhook url configured"}
    if not webhook_url.startswith("https://hooks.slack.com/"):
        return {"sent": False,
                "reason": "webhook url does not look like a Slack incoming webhook"}
    try:
        import httpx
    except ImportError:
        return {"sent": False, "reason": "httpx not installed (pip install "
                                          "'safecadence-netrisk[ai]' or [server])"}
    payload = _format_slack_blocks(events)
    try:
        with httpx.Client(timeout=timeout) as client:
            r = client.post(webhook_url, json=payload)
        return {
            "sent": 200 <= r.status_code < 300,
            "status": r.status_code,
            "reason": r.text[:200] if r.status_code >= 400 else "ok",
            "events_sent": len(events),
        }
    except Exception as e:
        return {"sent": False, "reason": f"{type(e).__name__}: {e}"}


def notify(webhook_url: str | None, events: list[dict],
            *, signing_secret: str | None = None) -> dict[str, Any]:
    """High-level dispatch — pick the right channel based on the URL.

    v7.2 dispatches to Slack / Microsoft Teams / PagerDuty / generic
    HMAC-signed webhook. A receiver that wants signature verification
    sets ``signing_secret`` and we compute the SHA-256 HMAC over the
    raw payload, send it in the X-SafeCadence-Signature header.
    """
    if not webhook_url:
        webhook_url = (os.environ.get("SC_SLACK_WEBHOOK")
                        or os.environ.get("SAFECADENCE_SLACK_WEBHOOK")
                        or os.environ.get("SC_WEBHOOK_URL"))
    if not webhook_url:
        return {"sent": False, "reason": "no webhook configured"}
    if "hooks.slack.com" in webhook_url:
        return notify_slack(webhook_url, events,
                              signing_secret=signing_secret)
    if "webhook.office.com" in webhook_url or "office.com/webhookb2" in webhook_url:
        return notify_teams(webhook_url, events,
                              signing_secret=signing_secret)
    if "events.pagerduty.com" in webhook_url:
        return notify_pagerduty(webhook_url, events,
                                  signing_secret=signing_secret)
    # Generic webhook — HMAC-signed JSON of the events list.
    return notify_generic(webhook_url, events,
                            signing_secret=signing_secret)


# --------------------------------------------------------------------------
# v7.2 — extra channels
# --------------------------------------------------------------------------

def _sign(payload_bytes: bytes, secret: str) -> str:
    import hashlib, hmac
    return ("sha256=" + hmac.new(secret.encode("utf-8"),
                                   payload_bytes, hashlib.sha256).hexdigest())


def _post_json(url: str, payload: dict, *, signing_secret: str | None = None,
                timeout: int = 10) -> dict:
    """POST a JSON payload, optionally HMAC-signed. Never raises."""
    try:
        import httpx
    except ImportError:
        return {"sent": False, "reason": "httpx not installed"}
    import json as _j
    body = _j.dumps(payload).encode("utf-8")
    headers = {"Content-Type": "application/json"}
    if signing_secret:
        headers["X-SafeCadence-Signature"] = _sign(body, signing_secret)
        headers["X-SafeCadence-Timestamp"] = str(int(__import__("time").time()))
    try:
        with httpx.Client(timeout=timeout) as client:
            r = client.post(url, content=body, headers=headers)
        return {"sent": 200 <= r.status_code < 300,
                "status": r.status_code,
                "reason": r.text[:200] if r.status_code >= 400 else "ok"}
    except Exception as e:
        return {"sent": False, "reason": f"{type(e).__name__}: {e}"}


def notify_teams(webhook_url: str, events: list[dict],
                  *, signing_secret: str | None = None,
                  timeout: int = 10) -> dict[str, Any]:
    """Microsoft Teams — Adaptive Card via Power Automate / Workflow
    Connectors. Builds a card with a per-event facts list."""
    if not events:
        return {"sent": False, "reason": "no events"}
    crit = sum(1 for e in events
               if (e.get("severity") or "").lower() == "critical")
    rank = {"critical": 0, "high": 1, "medium": 2, "low": 3, "info": 4}
    sorted_events = sorted(
        events, key=lambda e: rank.get((e.get("severity") or "info").lower(), 5),
    )
    facts = []
    for e in sorted_events[:10]:
        sev = (e.get("severity") or "info").upper()
        title = e.get("title") or e.get("type") or "finding"
        asset = e.get("asset_id") or ""
        facts.append({"name": f"[{sev}] {title}",
                       "value": (asset + " — "
                                  + (e.get("why") or e.get("conflict") or "").strip())[:300]})
    card = {
        "type": "message",
        "attachments": [{
            "contentType": "application/vnd.microsoft.card.adaptive",
            "content": {
                "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
                "type": "AdaptiveCard", "version": "1.4",
                "body": [
                    {"type": "TextBlock", "size": "Large", "weight": "Bolder",
                     "text": f"SafeCadence — {len(events)} new findings "
                              f"({crit} critical)",
                     "color": "Attention" if crit else "Default"},
                    {"type": "FactSet", "facts": facts},
                ],
            },
        }],
    }
    return _post_json(webhook_url, card, signing_secret=signing_secret,
                       timeout=timeout)


def notify_pagerduty(webhook_url: str, events: list[dict],
                      *, signing_secret: str | None = None,
                      timeout: int = 10) -> dict[str, Any]:
    """PagerDuty Events API v2. Each SafeCadence event becomes a
    separate PagerDuty incident. The webhook URL is actually the
    Events API ingestion endpoint plus the routing key in the body.
    Caller stuffs the routing key into the URL like
    ``https://events.pagerduty.com/v2/enqueue?routing_key=<key>``."""
    if not events:
        return {"sent": False, "reason": "no events"}
    from urllib.parse import urlparse, parse_qs
    parsed = urlparse(webhook_url)
    qs = parse_qs(parsed.query)
    routing_key = (qs.get("routing_key") or [""])[0]
    if not routing_key:
        return {"sent": False,
                "reason": "PagerDuty webhook URL must include routing_key=..."}
    base = f"{parsed.scheme}://{parsed.netloc}{parsed.path}"
    statuses: list[dict] = []
    for e in events:
        sev = (e.get("severity") or "info").lower()
        pd_severity = {"critical": "critical", "high": "error",
                        "medium": "warning", "low": "info",
                        "info": "info"}.get(sev, "info")
        payload = {
            "routing_key": routing_key,
            "event_action": "trigger",
            "dedup_key": (e.get("dedup_key")
                           or f"sc-{e.get('asset_id','')}-{e.get('control_id','')}")[:255],
            "payload": {
                "summary": (e.get("title") or e.get("type") or "SafeCadence finding")[:1024],
                "severity": pd_severity,
                "source": e.get("asset_id") or "safecadence",
                "component": e.get("source") or "policy",
                "class": e.get("type") or "compliance",
                "custom_details": {
                    k: e.get(k) for k in
                    ("why", "conflict", "evidence", "policy_id", "control_id",
                     "resolution") if e.get(k)
                },
            },
        }
        statuses.append(_post_json(base, payload,
                                     signing_secret=signing_secret,
                                     timeout=timeout))
    return {
        "sent": all(s.get("sent") for s in statuses),
        "events_sent": sum(1 for s in statuses if s.get("sent")),
        "statuses": statuses[:5],
    }


def notify_generic(webhook_url: str, events: list[dict],
                    *, signing_secret: str | None = None,
                    timeout: int = 10) -> dict[str, Any]:
    """Generic HMAC-signed webhook for arbitrary receivers. Posts the
    raw events list as JSON. Receivers verify with the same secret."""
    return _post_json(webhook_url, {
        "tool": "safecadence", "version": "7.2.0",
        "event_count": len(events), "events": events,
    }, signing_secret=signing_secret, timeout=timeout)


# --------------------------------------------------------- Splunk (v9.24)

def notify_splunk_hec(hec_url: str, hec_token: str, events: list[dict],
                        *, source: str = "safecadence",
                        sourcetype: str = "safecadence:event",
                        index: str | None = None,
                        timeout: int = 10) -> dict[str, Any]:
    """Push events into Splunk via HTTP Event Collector (HEC).

    HEC accepts a stream of newline-delimited JSON envelopes, each
    wrapping the actual payload under an 'event' key. We batch all
    events in one POST — Splunk parses them as separate events.

    Args:
        hec_url: full HEC endpoint, e.g.
                 ``https://splunk.example.com:8088/services/collector``
        hec_token: HEC token from Splunk's Data Inputs config
        events: list of event dicts (findings, score changes, etc.)
        source: Splunk 'source' field — searchable as ``source=...``
        sourcetype: Splunk 'sourcetype' — controls field extraction
        index: optional Splunk index to write to; if omitted, the
               token's default index is used
        timeout: HTTP timeout in seconds

    Returns:
        ``{"sent": bool, "status": int, "reason": str, "events": int}``
        — never raises so the daemon's notify loop stays alive.

    Shape is intentionally aligned with the other notifiers in this
    module so it's a one-line swap in the existing fan-out.
    """
    if not events:
        return {"sent": False, "reason": "no events"}
    try:
        import httpx
    except ImportError:
        return {"sent": False, "reason": "httpx not installed"}

    import json as _j
    import time as _t
    now = _t.time()

    # Newline-delimited HEC envelope. One JSON object per event.
    parts: list[str] = []
    for ev in events:
        envelope: dict[str, Any] = {
            "time": ev.get("timestamp") or now,
            "host": ev.get("host") or ev.get("asset_id") or "safecadence",
            "source": source,
            "sourcetype": sourcetype,
            "event": ev,
        }
        if index:
            envelope["index"] = index
        parts.append(_j.dumps(envelope))
    body = "\n".join(parts).encode("utf-8")
    headers = {
        "Authorization": f"Splunk {hec_token}",
        "Content-Type": "application/json",
    }

    try:
        with httpx.Client(timeout=timeout, verify=True) as client:
            r = client.post(hec_url, content=body, headers=headers)
        ok = 200 <= r.status_code < 300
        return {
            "sent": ok,
            "status": r.status_code,
            "reason": "ok" if ok else r.text[:200],
            "events": len(events),
        }
    except Exception as e:
        return {"sent": False, "reason": f"{type(e).__name__}: {e}",
                "events": len(events)}
