"""Markdown report renderer.

Designed to look great when piped into a file or rendered by a Markdown
viewer. The rich-formatted CLI output lives in cli.py — this module
produces *portable* Markdown.
"""

from __future__ import annotations

from safecadence.core.schema import Finding, ScanResult, Severity


_SEV_LABEL = {
    Severity.CRITICAL: "CRITICAL",
    Severity.HIGH:     "HIGH",
    Severity.MEDIUM:   "MEDIUM",
    Severity.LOW:      "LOW",
    Severity.INFO:     "INFO",
}


def _finding_md(f: Finding) -> str:
    parts = [
        f"### `{f.severity.value.upper()}` — {f.title}",
        "",
        f"- **Rule:** `{f.rule_id}`",
        f"- **Domain:** {f.domain}",
    ]
    if f.evidence and f.evidence != "(absent)":
        parts.append(f"- **Evidence:** `{f.evidence}`")
    parts.append("")
    if f.description:
        parts.append(f.description.strip())
        parts.append("")
    if f.remediation:
        parts.append("**Remediation**")
        parts.append("")
        parts.append(f.remediation.strip())
        parts.append("")
    if f.fix_snippet:
        parts.append("**Suggested config**")
        parts.append("")
        parts.append("```")
        parts.append(f.fix_snippet.strip())
        parts.append("```")
        parts.append("")
    if f.references:
        parts.append("**References**")
        parts.append("")
        for r in f.references:
            parts.append(f"- {r}")
        parts.append("")
    return "\n".join(parts)


def to_markdown(result: ScanResult) -> str:
    p = result.parsed
    lines: list[str] = []
    lines.append(f"# SafeCadence Scan Report — {p.hostname or result.source}")
    lines.append("")
    lines.append(f"_Generated {result.started_at}_  ")
    lines.append("")
    lines.append("## Device")
    lines.append("")
    lines.append("| Field | Value |")
    lines.append("|---|---|")
    lines.append(f"| Source | `{result.source}` |")
    lines.append(f"| Vendor | {result.vendor} |")
    lines.append(f"| Hostname | {p.hostname or '—'} |")
    lines.append(f"| Model | {p.model or '—'} |")
    lines.append(f"| OS | {p.os or '—'} |")
    lines.append(f"| Version | {p.version or '—'} |")
    lines.append(f"| Interfaces | {len(p.interfaces)} |")
    lines.append(f"| Neighbors | {len(p.neighbors)} |")
    lines.append("")
    lines.append("## Scores")
    lines.append("")
    lines.append("| Metric | Score | Band |")
    lines.append("|---|---|---|")
    lines.append(f"| Health | **{result.health_score}** / 100 | {result.health_band} |")
    lines.append(f"| Risk   | **{result.risk_score}** / 100 | {result.risk_band} |")
    lines.append("")
    lines.append(f"_Summary:_ {result.summary}")
    lines.append("")
    lines.append("## Findings")
    lines.append("")
    if not result.findings:
        lines.append("_No findings._ Either a clean device, or no rules matched.")
        lines.append("")
    else:
        for sev in (Severity.CRITICAL, Severity.HIGH, Severity.MEDIUM, Severity.LOW, Severity.INFO):
            bucket = [f for f in result.findings if f.severity == sev]
            if not bucket:
                continue
            lines.append(f"## {_SEV_LABEL[sev]} ({len(bucket)})")
            lines.append("")
            for f in bucket:
                lines.append(_finding_md(f))
    crit_count = sum(1 for f in result.findings if f.severity == Severity.CRITICAL)
    if result.risk_score >= 80 or crit_count >= 5:
        lines.append("---")
        lines.append("")
        lines.append("## Need help fixing these?")
        lines.append("")
        lines.append("This device shows a critical risk profile. **SafeCadence offers "
                     "end-to-end remediation engagements** — prioritized fix plan, "
                     "implementation support, and post-change validation. We work with "
                     "the same open-source engine you just ran — no lock-in, no SaaS, "
                     "no data leaves your environment.")
        lines.append("")
        subject = (result.parsed.hostname or result.source).replace(" ", "%20")
        lines.append(f"- **Email:** [hello@safecadence.com](mailto:hello@safecadence.com?subject=SafeCadence%20Remediation%20-%20{subject})")
        lines.append("- **Website:** https://safecadence.com")
        lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("_Generated by [SafeCadence Network Risk](https://safecadence.com) "
                 "— open-source, BYOK AI, free at your own risk._")
    return "\n".join(lines)
